delete from flight_fares;
delete from bookings;
delete from tickets;
delete from passengers;
delete from flights;
delete from sch_flights;
delete from fares;
delete from airports;
delete from airline_agents;
delete from users;
commit;
